### ISSUE TITLE
ECONNRESET issue

### ISSUE THREAD

**Issue by EarlVadim** [BScrk/zecproxy#12]
**Hello.
I permanently get this error.  Windows10x64 with nodejs**

`2018/01/24 11:49:19 INFO # Work from t1PtCxxxxxxxxxxxxxxxxBt3Lt.ZCLGreen accepted
2018/01/24 11:49:29 INFO # Submit work for t1PtCxxxxxxxxxxxxxxxxBt3Lt.ZCLGreen
2018/01/24 11:49:30 INFO # Work from t1PtCxxxxxxxxxxxxxxxxBt3Lt.ZCLGreen accepted
2018/01/24 11:49:34 INFO # Submit work for t1PtCxxxxxxxxxxxxxxxxBt3Lt.ZCLGreen
2018/01/24 11:49:34 INFO # Work from t1PtCxxxxxxxxxxxxxxxxBt3Lt.ZCLGreen accepted
2018/01/24 11:49:54 ERROR # Network error, Error: read ECONNRESET
2018/01/24 11:49:54 INFO # Connecting to zec-eu1.nanopool.org:6666
2018/01/24 11:49:55 INFO # Connected to pool zec-eu1.nanopool.org:6666
2018/01/24 11:49:55 WARN # Creating workers listner...
2018/01/24 11:49:55 INFO # Subscribing to pool...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at new MinersController (C:\zecproxy\lib\miners_controller.js:23:8)
    at PoolConnector.onConnect (C:\zecproxy\lib\pool_connector.js:32:27)
    at Socket.poolSocket.on (C:\zecproxy\lib\pool_connector.js:161:60)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zecproxy@1.0.8 start: `node proxy.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zecproxy@1.0.8 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2018-01-24T08_49_55_171Z-debug.log`

**log**

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle zecproxy@1.0.8~prestart: zecproxy@1.0.8
6 info lifecycle zecproxy@1.0.8~start: zecproxy@1.0.8
7 verbose lifecycle zecproxy@1.0.8~start: unsafe-perm in lifecycle true
8 verbose lifecycle zecproxy@1.0.8~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\zecproxy\node_modules\.bin;C:\Users\User\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\MSI Afterburner\;;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\nodejs\;C:\Users\User\AppData\Local\Microsoft\WindowsApps;C:\Users\User\AppData\Roaming\npm
9 verbose lifecycle zecproxy@1.0.8~start: CWD: C:\zecproxy
10 silly lifecycle zecproxy@1.0.8~start: Args: [ '/d /s /c', 'node proxy.js' ]
11 silly lifecycle zecproxy@1.0.8~start: Returned: code: 1  signal: null
12 info lifecycle zecproxy@1.0.8~start: Failed to exec start script
13 verbose stack Error: zecproxy@1.0.8 start: `node proxy.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid zecproxy@1.0.8
15 verbose cwd C:\zecproxy
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error zecproxy@1.0.8 start: `node proxy.js`
22 error Exit status 1
23 error Failed at the zecproxy@1.0.8 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by BScrk** [comment]
Thanks, we'll take a look

**Comment by TheComputerGenie** [comment]
> Error: listen EADDRINUSE :::8000

means that you need to change the `port` in config because you already have something using that port
