### ISSUE TITLE
requirements?

### ISSUE THREAD

**Issue by kruisdraad** [BScrk/zecproxy#3]
Hi, could you list package requirements and versions (e.g. nodejs)

olSocket = tls.connect(this.current_pool.port, this.current_pool.host, () => {
                                                                        ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/zecproxy/proxy.js:2:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

on a latest PI installation. looks like i am missing something?

**Comment by jimmywinberg** [comment]
I have the same problem.
Raspberry pi 3, installed npm and node, still same problem.

**Comment by jimmywinberg** [comment]
/home/pi/zecproxy/lib/pool_connector.js:137
olSocket = tls.connect(this.current_pool.port, this.current_pool.host, () => {
^
SyntaxError: Unexpected token )
at Module._compile (module.js:439:25)
at Object.Module._extensions…js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object. (/home/pi/zecproxy/proxy.js:2:18)
at Module._compile (module.js:456:26)
at Object.Module._extensions…js (module.js:474:10)
at Module.load (module.js:356:32)

**Comment by kruisdraad** [comment]
install nodejs7 from repo and it works

at least it starts ... the proxy is full of bugs and you actually make less money with it.

**Comment by jimmywinberg** [comment]
What pool have you tried the proxy at?
And what is the command to install the nodejs7 ? Sorry im new

**Comment by BScrk** [comment]
> what is the command to install the nodejs7 ?

On Debian/Ubuntu/Raspbian :

- `sudo apt update`
- `sudo apt install nodejs`


> The proxy is full of bugs and you actually make less money with it.
> What pool have you tried the proxy at?

Don't use the proxy with Flypool, or other misconfigured pool... (rejecting shares after they tried to raised shares difficulty, don't allow proper hashrate aggregation, workers identification etc...) Prefer Nanopool, Dwarf or other well setuped pools.

**Comment by BScrk** [comment]
... or use this script from Linda [forum.z.cash](https://forum.z.cash/t/zcash-stratum-proxy-increase-earning-up-to-10/22113/46) :)
